name: Bug report
description: Create a report to help us improve
labels: [bug]
body:
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: What happened and what did you expect?
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Steps to reproduce
      description: Provide steps to reproduce the behavior.
      placeholder: 1) ..., 2) ..., 3) ...
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: App version
      placeholder: e.g. v0.1.0
  - type: dropdown
    id: os
    attributes:
      label: OS
      multiple: true
      options:
        - Windows
        - macOS
        - Linux
  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: Paste any relevant logs or screenshots.


