name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - uses: dtolnay/rust-toolchain@stable
      - uses: swatinem/rust-cache@v2
      - name: Install deps
        run: npm ci
      - name: Type check & web build
        run: npm run build
      - name: Unit tests
        run: npm test -- --run
      - name: Cargo check
        run: |
          cd src-tauri
          cargo check --release


